# Generated by Django 2.1.2 on 2018-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCapabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('task_level', models.IntegerField()),
                ('task_helpers', models.BooleanField()),
                ('task_points', models.BooleanField()),
            ],
        ),
    ]
