# Generated by Django 2.1.2 on 2018-12-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
                ('level', models.IntegerField(choices=[(0, 'Podstawowy'), (1, 'Normalny'), (2, 'Średni'), (3, 'Średniozaawansowany'), (4, 'Zaawansowany')])),
                ('urgent', models.IntegerField(choices=[(0, 'Bardzo Wolny'), (1, 'Wolny'), (2, 'Normalny'), (3, 'Szybki'), (4, 'Bardzo Szybki')])),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('helpers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sprint.Sprint')),
                ('worker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
